### ISSUE TITLE
Numpy int patch not reflected in lws-1.2.7.tar.gz

### ISSUE THREAD

**Issue by bertrandclim** [Jonathan-LeRoux/lws#16]
The fix several months ago replacing "np.int" with "int" (https://github.com/Jonathan-LeRoux/lws/pull/15) is not reflected in ./python/dist/lws-1.2.7.tar.gz, so pip installation from pypi (without cython build) fails for recent numpy versions since np.int was removed. The install still works with "cd python; make sdist; pip install dist/lws-1.2.7.tar.gz" as stated in ./python/readme.md.

**Comment by Jonathan-LeRoux** [comment]
Thanks a lot for pointing this out, I had completely forgotten about creating a new release and updating pypi. The new 1.2.8 release should be fixed, and is now live on pypi. Please let me know if you see any issue.
