### ISSUE TITLE
Failed to install on Windows 10 (x64) using pip install

### ISSUE THREAD

**Issue by d2sys** [Jonathan-LeRoux/lws#4]
pip install lws
Collecting lws
  Downloading lws-1.2.tar.gz (133kB)
    100% |████████████████████████████████| 143kB 778kB/s
Building wheels for collected packages: lws
  Running setup.py bdist_wheel for lws ... error
  Complete output from command C:\Anaconda3\envs\pt\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\data2\\AppData\\Local\\Temp\\pip-build-hpsw5y8h\\lws\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\data2\AppData\Local\Temp\tmpmy25klczpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'lws' extension
  creating build
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\lwslib
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ilwslib/ -IC:\Anaconda3\envs\pt\lib\site-packages\numpy\core\include -IC:\Anaconda3\envs\pt\include -IC:\Anaconda3\envs\pt\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.12.25827\include" /EHsc /Tplws.bycython.cpp /Fobuild\temp.win-amd64-3.6\Release\lws.bycython.obj -O3
  cl : Command line warning D9002 : ignoring unknown option '-O3'
  lws.bycython.cpp
  c:\anaconda3\envs\pt\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for lws
  Running setup.py clean for lws
Failed to build lws
Installing collected packages: lws
  Running setup.py install for lws ... error
    Complete output from command C:\Anaconda3\envs\pt\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\data2\\AppData\\Local\\Temp\\pip-build-hpsw5y8h\\lws\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\data2\AppData\Local\Temp\pip-sb1ltnj5-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'lws' extension
    creating build
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\lwslib
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ilwslib/ -IC:\Anaconda3\envs\pt\lib\site-packages\numpy\core\include -IC:\Anaconda3\envs\pt\include -IC:\Anaconda3\envs\pt\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.12.25827\include" /EHsc /Tplws.bycython.cpp /Fobuild\temp.win-amd64-3.6\Release\lws.bycython.obj -O3
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    lws.bycython.cpp
    c:\anaconda3\envs\pt\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Anaconda3\envs\pt\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\data2\\AppData\\Local\\Temp\\pip-build-hpsw5y8h\\lws\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\data2\AppData\Local\Temp\pip-sb1ltnj5-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\data2\AppData\Local\Temp\pip-build-hpsw5y8h\lws\

**Comment by Jonathan-LeRoux** [comment]
There seems to be quite a few posts online about issues with pip on Windows 10, you can try googling "pyconfig.h  Cannot open include file: 'io.h'". For example, this [comment on Github](https://github.com/pandas-dev/pandas/issues/981#issuecomment-362896442) and this [StackOverflow post](https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory) look relevant.
I only have Windows 7 and 8.1 available, so I haven't run into this issue.

**Comment by ZubairKhan001** [comment]
add the windows 10 sdk in the path
