### ISSUE TITLE
setup.py does not specify dependencies

### ISSUE THREAD

**Issue by rbarghou** [Jonathan-LeRoux/lws#6]
I'm attempting to write a pip package that depends on lws, but unfortunately, doing so results in a circular dependency issue because `lws` does not explicitly list its dependencies in the `setup.py`

I propose a small change to the `python/setup.py` file to add the line 
```python
setup(
    ...
    install_requires=["numpy"]
    ...
)
```
Otherwise, the lws setup.py file gets run by pip before the numpy package is satisfied.  This results in an import error.

**Comment by rbarghou** [comment]
Actually, I'm realizing that that won't work either.

This actually needs to use a `cmdclass` config to specify a post-install command and then move the import of numpy and depending lines into that command.  That way the numpy import doesn't happen without numpy installed in an environment.

If you don't have the time I can fork and write a PR into your project.

**Comment by Jonathan-LeRoux** [comment]
Thanks for noticing this. I was going to suggest adding a requirements.txt file, but that probably wouldn't cut it. Why wouldn't the install_requires work?
You are more than welcome to write a PR, I think this would take me more time than I can afford now as I'm not super familiar with such requirement issues.

**Comment by rbarghou** [comment]
Sure.  I'm going to try to get to it this weekend.  It probably isn't very hard, I just have to look into setuptools cmdclass option and see if it would accomplish what I want it too.

The reason that install_requires wouldn't work by itself is that the import of numpy happens before the setup function is called.

I'll see what I can pull together this weekend.  Thanks for responding.

**Comment by Jonathan-LeRoux** [comment]
> The reason that install_requires wouldn't work by itself is that the import of numpy happens before the setup function is called.
Does this only happen when using cython? The pip install shouldn't run into this kind of problem, right?

**Comment by rbarghou** [comment]
I think pip will run into this too.  It happens when I attempt to run setup using `pip` on my package.  But I haven't published my package to pypi yet.  But even still, pip has to load the setup.py module and that should fail with the `import numpy` at the module level.

**Comment by Jonathan-LeRoux** [comment]
Ah, yes, sorry, I had forgotten about the `import numpy` bit inside setup.py itself for the np.get_include() call. If you know how to solve this, that would be great indeed!

**Comment by rbarghou** [comment]
Well, it turns out that I couldn't directly solve it, but that pip provides the workaround on my end.  Once I've built my package into a wheel, the necessary requirements are resolved in the desirable order... I think.

I'm going to play around with it some more, but I don't think I need anything done with your package.

I really appreciate you taking the time to look at it.  I think you might still have other people who run into this problem if they try to use your app as a dependency.  But I think if they're just trying to build a system, they can just manage the install order manually, and otherwise, they can build a wheel as part of a deployment process.

If I find out a good way to resolve this in your app, I'll put in a PR.  In the mean time, I'm going to close this issue.

**Comment by Julian** [comment]
Running into the same issue here.

I don't really know the paradigm within the numpy community, a first read of the setup.py here says all it's being used for is likely to locate a C include directory or something?

But as is, at very least it should be in *`setup_requires`*, (as well as `install_requires`), because as written, yeah, I get errors even trying to install this (I think as a transitive dep of autokeras), since it's trying to import numpy before numpy is installed.

**Comment by Jonathan-LeRoux** [comment]
Indeed, numpy is really only imported to get its proper library location.
It looks like this [response on StackOverflow](https://stackoverflow.com/a/42163080/1839106) is addressing the issue. I won't have time to look at this for another couple weeks, but if you get to give it a try by then, please let me know how it went.
