### ISSUE TITLE
FileNotFoundError (_version.py) while installing library

### ISSUE THREAD

**Issue by MariaMsu** [Jonathan-LeRoux/lws#8]
```
pip install lws
Collecting lws
  Using cached https://files.pythonhosted.org/packages/ee/14/b1d07a911f7e50f5c2d8ab1b65021a79232eb6267cba203afe20e50b3caa/lws-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-slr12ijc/lws/setup.py", line 27, in <module>
        verstrline = open(VERSIONFILE, "rt").read()
      File "/home/mcherepnina/anaconda3/lib/python3.7/codecs.py", line 898, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '_version.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-slr12ijc/lws/
```

**Comment by Jonathan-LeRoux** [comment]
Thanks for reporting. I added _version.py, can you try again?

**Comment by Jonathan-LeRoux** [comment]
Oops, I think I got something wrong, please give me a few more minutes.

**Comment by Jonathan-LeRoux** [comment]
Alright, we should be good now. Note to self for later: don't do things in a hurry :)

**Comment by MariaMsu** [comment]
well, almost working...

I can install, but:
```
>>> import lws
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lws.pyx", line 6, in init lws
ModuleNotFoundError: No module named '_version'
```

**Comment by Jonathan-LeRoux** [comment]
I'll try to look at this later today, in the mean time, you can use version 1.2 (if you're on a Mac, you'll need to follow the fix in https://github.com/Jonathan-LeRoux/lws/issues/7).

**Comment by Jonathan-LeRoux** [comment]
I think it should work now. I tested installation from pip in Python 2.7, 3.6, and 3.7.

**Comment by MariaMsu** [comment]
Yes, everything works, thanks :)

**Comment by rishabh004-ai** [comment]
This is the error when i am running colab notebook for Deep Voice 3. 
Building wheel for lws (setup.py) ... error
  ERROR: Failed building wheel for lws
    Running setup.py install for lws ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fk8kaa5j/lws/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fk8kaa5j/lws/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uptda2pk/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by Jonathan-LeRoux** [comment]
There isn't much in terms of error messages for me to figure out what is going on... Do you have a way to check the logs for full command output as mentioned?
